// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ferruvich/curve-challenge/internal/repo (interfaces: Merchant)

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	model "github.com/ferruvich/curve-challenge/api/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMerchant is a mock of Merchant interface
type MockMerchant struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantMockRecorder
}

// MockMerchantMockRecorder is the mock recorder for MockMerchant
type MockMerchantMockRecorder struct {
	mock *MockMerchant
}

// NewMockMerchant creates a new mock instance
func NewMockMerchant(ctrl *gomock.Controller) *MockMerchant {
	mock := &MockMerchant{ctrl: ctrl}
	mock.recorder = &MockMerchantMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMerchant) EXPECT() *MockMerchantMockRecorder {
	return m.recorder
}

// Write mocks base method
func (m *MockMerchant) Write(arg0 context.Context, arg1 *model.Merchant) error {
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockMerchantMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMerchant)(nil).Write), arg0, arg1)
}
